services:
    leoo_team.cache_cleaner.command_listener:
        class: 'LeooTeam\CacheCleanerBundle\Event\CommandListener'
        arguments:
            - "@=container.hasParameter('leoo_team_cache_cleaner.commands') ? parameter('leoo_team_cache_cleaner.commands') : []"
        tags:
            - { name: kernel.event_listener, event: 'console.command', method: 'run' }
